dist: trusty
language: groovy
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

before_install:
  - docker pull mongo:3.4
  - docker run -d -p '27017:27017' --name travis-mongo mongo:3.4

script:
  ./gradlew check --exclude-task composeUp --exclude-task composeDown

after_success:
  - if [[ -v $TRAVIS_TAG ]]; then ./docker/docker_push.sh; fi

# called out in Travis documentations (https://docs.travis-ci.com/user/languages/groovy#Gradle-Caching)
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
