dist: trusty
language: groovy
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

before_install:
  - docker pull mongo:3.4
  - docker run -d -p '27017:27017' --name travis-mongo mongo:3.4

script:
  ./gradlew check --exclude-task composeUp --exclude-task composeDown

after_success:
  - if [[ -n "$TRAVIS_TAG" ]]; then
    echo "building brickster/my-box:$TRAVIS_TAG";
    mv build/libs/my-box-1.0-SNAPSHOT.jar docker/app.jar;
    cd docker;
    docker build -t brickster/my-box -t brickster/my-box:$TRAVIS_TAG .;
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
    docker push brickster/my-box;
    fi

# called out in Travis documentations (https://docs.travis-ci.com/user/languages/groovy#Gradle-Caching)
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
