api.version: 1.0.1

spring:
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      host: my-box-mongo

# disable all but health and info actuator endpoints
endpoints:
  enabled: false
  info.enabled: true
  health.enabled: true

# allow sensitive health indicators
management.security.enabled: false
management.health.diskspace.enabled: false
endpoints.health.sensitive: true

# CORS settings for actuator endpoints
endpoints.cors.allowed-origins: ${swagger-ui.url}

server.contextPath: /my-box/v1
server.error.whitelabel.enabled: false

swagger-ui.url: http://localhost:8090
