version: '2'
services:
  my-box-mongo:
    image: mongo:3.4
    container_name: my-box-mongo
    ports:
      - '27017:27017'
  my-box-swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: my-box-swagger-ui
    ports:
      - '8090:8080'
    environment:
      - 'API_URL=http://localhost:8080/my-box/v1/swagger.yml'
